### PR TITLE
Add `no-floating-promises`

### PR DESCRIPTION
**Pull request by petermanser**

### CODE REVIEW

**Comment by petermanser** [comment]
@buehler probably a "breaking" change?

**Comment by petermanser** [comment]
@nmaro fyi

**Comment by buehler** [comment]
@petermanser Yea I assume this is a breaking change since the rules are stricter and are possibly breaking builds.

**Comment by buehler** [comment]
lgtm
:shipit:

**Review by buehler — APPROVED** [review]

**Pull request merged**
